# Generated by Django 4.2.7 on 2025-07-04 00:08

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('specialite', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(choices=[('administrateur', 'Administrateur'), ('medecin', 'Medecin'), ('user_simple', 'User Simple')], max_length=50)),
                ('statut', models.CharField(blank=True, max_length=50, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Analyse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeAnalyse', models.CharField(max_length=255)),
                ('dateAnalyse', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Comportement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viePrivee', models.CharField(blank=True, max_length=255, null=True)),
                ('mangeAilleursMain', models.CharField(blank=True, max_length=255, null=True)),
                ('vieAvecAussiEnfantDeManger', models.CharField(blank=True, max_length=255, null=True)),
                ('utiliseSalon', models.CharField(blank=True, max_length=255, null=True)),
                ('laveLesMainsEnfants', models.CharField(blank=True, max_length=255, null=True)),
                ('utiliseSallyHydroalcoolique', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DossierMedical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomDossier', models.CharField(max_length=255)),
                ('dateCreation', models.DateField(auto_now_add=True)),
                ('commentaireGeneral', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(default='Actif', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Logement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeLogement', models.CharField(max_length=255)),
                ('nombrePersonnesFoyer', models.IntegerField()),
                ('multiMaisonsCouverts', models.CharField(blank=True, max_length=10, null=True)),
                ('sousMaisonCouverts', models.CharField(blank=True, max_length=10, null=True)),
                ('toilettesInterieures', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('dateNaissance', models.DateField()),
                ('sexe', models.CharField(max_length=10)),
                ('poids', models.FloatField(blank=True, null=True)),
                ('taille', models.FloatField(blank=True, null=True)),
                ('lieuNaissance', models.CharField(blank=True, max_length=255, null=True)),
                ('nationalite', models.CharField(blank=True, max_length=255, null=True)),
                ('niveauEtude', models.CharField(blank=True, max_length=255, null=True)),
                ('etablissement', models.CharField(blank=True, max_length=255, null=True)),
                ('comportement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.comportement')),
                ('logement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.logement')),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomProfession', models.CharField(max_length=255)),
                ('typeProfession', models.CharField(blank=True, max_length=255, null=True)),
                ('environnementTravail', models.CharField(blank=True, max_length=255, null=True)),
                ('travailleChezSoi', models.CharField(blank=True, max_length=10, null=True)),
                ('travailleDansEmploi', models.CharField(blank=True, max_length=10, null=True)),
                ('revenu', models.FloatField(blank=True, null=True)),
                ('freqRevenu', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegleConformite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomRegle', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('typeRegle', models.CharField(max_length=255)),
                ('niveauCritique', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Residence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pays', models.CharField(max_length=255)),
                ('ville', models.CharField(max_length=255)),
                ('quartier', models.CharField(max_length=255)),
                ('adresseComplete', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomVaccin', models.CharField(max_length=255)),
                ('typeVaccin', models.CharField(max_length=255)),
                ('dateVaccination', models.DateField()),
                ('dose', models.CharField(max_length=255)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.patient')),
            ],
        ),
        migrations.CreateModel(
            name='ResultatAnalyse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateAnalyse', models.DateField()),
                ('glycemie', models.FloatField(blank=True, null=True)),
                ('hemoglobine', models.FloatField(blank=True, null=True)),
                ('leucocytes', models.FloatField(blank=True, null=True)),
                ('lymphocytes', models.FloatField(blank=True, null=True)),
                ('neutrophiles', models.FloatField(blank=True, null=True)),
                ('analyse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.analyse')),
            ],
        ),
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateRapport', models.DateField(auto_now_add=True)),
                ('titre', models.CharField(max_length=255)),
                ('statut', models.CharField(default='Brouillon', max_length=50)),
                ('contenu', models.TextField(blank=True, null=True)),
                ('statutConformite', models.CharField(default='Non évalué', max_length=50)),
                ('niveauConformite', models.IntegerField(blank=True, null=True)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dossiermedical')),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='profession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.profession'),
        ),
        migrations.AddField(
            model_name='patient',
            name='residence',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.residence'),
        ),
        migrations.CreateModel(
            name='ParametreConformite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('seuilMin', models.FloatField()),
                ('seuilMax', models.FloatField()),
                ('unite', models.CharField(max_length=50)),
                ('regle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.regleconformite')),
            ],
        ),
        migrations.CreateModel(
            name='Infection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomInfection', models.CharField(max_length=255)),
                ('typeInfection', models.CharField(max_length=255)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.patient')),
            ],
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.patient'),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='analyse',
            name='dossier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dossiermedical'),
        ),
        migrations.CreateModel(
            name='Alimentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeRepas', models.CharField(max_length=255)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeAlerte', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('dateAlerte', models.DateField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Acces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeAcces', models.CharField(max_length=255)),
                ('dateAcces', models.DateField()),
                ('rapport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.rapport')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
