# Generated by Django 4.2.7 on 2025-07-12 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_patient_id_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='residence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.residence'),
        ),
    ]
