# Generated by Django 4.2.7 on 2025-07-12 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_patient_residence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infection',
            name='nomInfection',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='infection',
            name='typeInfection',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vaccin',
            name='dose',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vaccin',
            name='nomVaccin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vaccin',
            name='typeVaccination',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
