# Generated by Django 4.2.7 on 2025-07-12 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_infection_nominfection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acces',
            name='typeAcces',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='alerte',
            name='typeAlerte',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='alimentation',
            name='typeRepas',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='typeAnalyse',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='comportement',
            name='laveLesMainsAvantDeManger',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='comportement',
            name='laveLesMainsDesEnfants',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='comportement',
            name='lieuRepas',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='comportement',
            name='mangeAvecLesMains',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='comportement',
            name='utiliseDuSavon',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='comportement',
            name='utiliseGelHydroalcoolique',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='infection',
            name='nomInfection',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='infection',
            name='typeInfection',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='logement',
            name='typeLogement',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='parametreconformite',
            name='nom',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id_code',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='lieuNaissance',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='niveauEtude',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='profession',
            name='environnementTravail',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='profession',
            name='freqRevenu',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='profession',
            name='nomProfession',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='profession',
            name='revenu',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='profession',
            name='situationSansEmploi',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='profession',
            name='travailleDehors',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='profession',
            name='travailleSansEmploi',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='profession',
            name='typeProfession',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='statutConformite',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='titre',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='regleconformite',
            name='nomRegle',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='regleconformite',
            name='typeRegle',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='residence',
            name='pays',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='residence',
            name='quartier',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='residence',
            name='ville',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='vaccin',
            name='nomVaccin',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='vaccin',
            name='typeVaccination',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
