# Generated by Django 4.2.7 on 2025-07-12 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_acces_typeacces_alter_alerte_typealerte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='residence',
            name='groupe',
            field=models.CharField(blank=True, help_text='Groupe de résidence (Urban, Semi-urban, Europe, etc.)', max_length=100, null=True),
        ),
    ]
