# Generated by Django 4.2.7 on 2025-07-12 23:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_residence_groupe'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeExportation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('APPROUVEE', 'Approuvée'), ('REFUSEE', 'Refusée')], default='EN_ATTENTE', max_length=20)),
                ('commentaire_medecin', models.TextField(blank=True, null=True)),
                ('donnees_autorisees', models.JSONField(default=dict, help_text="Types de données autorisées pour l'export")),
                ('demandeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_exportation', to=settings.AUTH_USER_MODEL)),
                ('medecin', models.ForeignKey(limit_choices_to={'role': 'MEDECIN'}, on_delete=django.db.models.deletion.CASCADE, related_name='demandes_a_traiter', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Demande d'exportation",
                'verbose_name_plural': "Demandes d'exportation",
                'ordering': ['-date_demande'],
            },
        ),
    ]
