# Generated by Django 4.2.7 on 2025-07-13 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_demandeexportation'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerte',
            name='donnees_concernees',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alerte',
            name='gravite',
            field=models.CharField(default='info', max_length=50),
        ),
        migrations.AddField(
            model_name='alerte',
            name='notifie_cdp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alerte',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parametreconformite',
            name='regle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parametres', to='api.regleconformite'),
        ),
        migrations.AlterField(
            model_name='alerte',
            name='dossier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.dossiermedical'),
        ),
    ]
