# Generated by Django 4.2.7 on 2025-07-13 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alerte_donnees_concernees_alerte_gravite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acces',
            name='donnees_concernees',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='acces',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='acces',
            name='regle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.regleconformite'),
        ),
    ]
