# Generated by Django 4.2.7 on 2025-07-15 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_acces_donnees_concernees_acces_utilisateur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='regleconformite',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
