# Generated by Django 4.2.7 on 2025-07-17 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_regleconformite_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeexportation',
            name='utilisee',
            field=models.BooleanField(default=False, help_text='Indique si la demande approuvée a déjà été utilisée pour exporter'),
        ),
    ]
