# Generated by Django 5.0.1 on 2024-12-19 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_demandeexportation_utilisee'),
    ]

    operations = [
        migrations.RunSQL(
            "DROP TABLE IF EXISTS api_passwordresettoken;",
            reverse_sql="-- Cette migration supprime la table, pas de rollback nécessaire"
        ),
    ]
