# Generated by Django 4.2.7 on 2025-07-19 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_password_reset_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acces',
            name='dateAcces',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
