# Generated by Django 4.2.7 on 2025-07-20 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_acces_dateacces'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='must_change_password',
            field=models.BooleanField(default=True, help_text="L'utilisateur doit changer son mot de passe à la première connexion"),
        ),
    ]
