# Generated by Django 4.2.7 on 2025-07-26 02:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_utilisateur_must_change_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlerteConformite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('details_techniques', models.JSONField(default=dict, help_text="Détails techniques de l'alerte")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('date_resolution', models.DateTimeField(blank=True, null=True)),
                ('date_notification_cdp', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('NOUVELLE', 'Nouvelle'), ('EN_COURS', 'En cours de traitement'), ('RESOLUE', 'Résolue'), ('ESCALADEE', 'Escaladée'), ('FERMEE', 'Fermée')], default='NOUVELLE', max_length=20)),
                ('niveau_critique', models.IntegerField(choices=[(1, 'Faible'), (2, 'Moyen'), (3, 'Élevé'), (4, 'Critique'), (5, 'Urgent')])),
                ('notifie_cdp', models.BooleanField(default=False)),
                ('notifie_dpo', models.BooleanField(default=False)),
                ('notifie_admin', models.BooleanField(default=False)),
                ('actions_prises', models.TextField(blank=True, null=True)),
                ('commentaires', models.TextField(blank=True, null=True)),
                ('donnees_concernees', models.JSONField(default=dict, help_text='Types de données concernées')),
                ('impact_patients', models.IntegerField(default=0, help_text='Nombre de patients impactés')),
                ('dossier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.dossiermedical')),
            ],
            options={
                'verbose_name': 'Alerte de conformité',
                'verbose_name_plural': 'Alertes de conformité',
                'ordering': ['-date_creation', '-niveau_critique'],
            },
        ),
        migrations.CreateModel(
            name='TypeAlerteConformite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(choices=[('RGPD_CONSENTEMENT_EXPIRE', 'Consentement RGPD expiré'), ('RGPD_DROIT_ACCES', "Demande de droit d'accès"), ('RGPD_DROIT_RECTIFICATION', 'Demande de droit de rectification'), ('RGPD_DROIT_EFFACEMENT', "Demande de droit d'effacement"), ('RGPD_DROIT_PORTABILITE', 'Demande de droit à la portabilité'), ('RGPD_DROIT_OPPOSITION', "Demande de droit d'opposition"), ('RGPD_VIOLATION_DONNEES', 'Violation de données personnelles'), ('RGPD_TRANSFERT_INTERNATIONAL', 'Transfert international de données'), ('RGPD_DPO_NOTIFICATION', 'Notification DPO requise'), ('HIPAA_PHI_ACCES_NON_AUTORISE', 'Accès non autorisé aux PHI'), ('HIPAA_BREACH_NOTIFICATION', 'Notification de violation HIPAA'), ('HIPAA_BA_NOTIFICATION', 'Notification Business Associate'), ('HIPAA_AUDIT_TRAIL_MANQUANT', 'Audit trail manquant'), ('HIPAA_ENCRYPTION_MANQUANT', 'Chiffrement manquant'), ('HIPAA_ACCESS_CONTROL_VIOLATION', "Violation de contrôle d'accès"), ('HIPAA_RETENTION_POLICY_VIOLATION', 'Violation de politique de rétention'), ('CDP_NOTIFICATION_VIOLATION', 'Notification CDP violation'), ('CDP_AUTORISATION_MANQUANT', 'Autorisation CDP manquante'), ('CDP_DROIT_PATIENT_VIOLATION', 'Violation des droits du patient'), ('CDP_SECRET_MEDICAL_VIOLATION', 'Violation du secret médical'), ('CDP_CONSENTEMENT_ECLAIRE', 'Consentement éclairé manquant'), ('ACCES_NON_AUTORISE', 'Accès non autorisé'), ('SUPPRESSION_ACCIDENTELLE', 'Suppression accidentelle'), ('MODIFICATION_NON_AUTORISEE', 'Modification non autorisée'), ('EXPORT_NON_AUTORISE', 'Export non autorisé'), ('CONSULTATION_EXCESSIVE', 'Consultation excessive'), ('SEUIL_MEDICAL_DEPASSE', 'Seuil médical dépassé'), ('BACKUP_MANQUANT', 'Sauvegarde manquante'), ('SECURITE_FAIBLE', 'Niveau de sécurité faible')], max_length=50, unique=True)),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('norme_conformite', models.CharField(choices=[('RGPD', 'RGPD'), ('HIPAA', 'HIPAA'), ('CDP', 'CDP Sénégal'), ('GENERAL', 'Général')], max_length=20)),
                ('niveau_critique', models.IntegerField(choices=[(1, 'Faible'), (2, 'Moyen'), (3, 'Élevé'), (4, 'Critique'), (5, 'Urgent')], default=3)),
                ('delai_notification', models.IntegerField(default=24, help_text='Délai en heures pour la notification')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': "Type d'alerte de conformité",
                'verbose_name_plural': "Types d'alertes de conformité",
                'ordering': ['norme_conformite', 'niveau_critique', 'nom'],
            },
        ),
        migrations.AlterModelOptions(
            name='alerte',
            options={'ordering': ['-dateAlerte', '-idAlerte']},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['idPatient']},
        ),
        migrations.CreateModel(
            name='RegleAlerteConformite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('conditions', models.JSONField(default=dict, help_text='Conditions de déclenchement')),
                ('seuil_min', models.IntegerField(blank=True, null=True)),
                ('seuil_max', models.IntegerField(blank=True, null=True)),
                ('periode_surveillance', models.IntegerField(default=24, help_text='Période en heures')),
                ('action_automatique', models.CharField(choices=[('NOTIFICATION', 'Notification automatique'), ('BLOQUER_ACCES', "Bloquer l'accès"), ('LOGGER', 'Enregistrer dans les logs'), ('ESCALADER', 'Escalader vers un supérieur'), ('FERMER_SESSION', 'Fermer la session')], default='NOTIFICATION', max_length=50)),
                ('notifier_admin', models.BooleanField(default=True)),
                ('notifier_dpo', models.BooleanField(default=False)),
                ('notifier_cdp', models.BooleanField(default=False)),
                ('notifier_medecin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('type_alerte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.typealerteconformite')),
            ],
            options={
                'verbose_name': "Règle d'alerte de conformité",
                'verbose_name_plural': "Règles d'alertes de conformité",
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='NotificationConformite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_notification', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('NOTIFICATION_INTERNE', 'Notification interne'), ('WEBHOOK', 'Webhook'), ('API', 'API externe')], max_length=20)),
                ('destinataire_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('destinataire_telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('sujet', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('contenu_html', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_envoi', models.DateTimeField(blank=True, null=True)),
                ('date_lecture', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ENVOYEE', 'Envoyée'), ('ECHEC', 'Échec'), ('LUE', 'Lue')], default='EN_ATTENTE', max_length=20)),
                ('tentatives', models.IntegerField(default=0)),
                ('erreur', models.TextField(blank=True, null=True)),
                ('alerte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.alerteconformite')),
                ('destinataire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification de conformité',
                'verbose_name_plural': 'Notifications de conformité',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.AddField(
            model_name='alerteconformite',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.patient'),
        ),
        migrations.AddField(
            model_name='alerteconformite',
            name='type_alerte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.typealerteconformite'),
        ),
        migrations.AddField(
            model_name='alerteconformite',
            name='utilisateur_origine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertes_origine', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alerteconformite',
            name='utilisateur_traitement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertes_traitement', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alerte',
            name='alerte_conformite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.alerteconformite'),
        ),
        migrations.CreateModel(
            name='AuditConformite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('type_action', models.CharField(choices=[('LECTURE', 'Lecture'), ('MODIFICATION', 'Modification'), ('SUPPRESSION', 'Suppression'), ('CREATION', 'Création'), ('EXPORT', 'Export'), ('IMPORT', 'Import'), ('ACCES', 'Accès'), ('CONNEXION', 'Connexion'), ('DECONNEXION', 'Déconnexion'), ('CHANGEMENT_PASSWORD', 'Changement de mot de passe'), ('MODIFICATION_PROFIL', 'Modification de profil')], max_length=20)),
                ('objet', models.CharField(help_text="Type d'objet concerné (Patient, Dossier, etc.)", max_length=100)),
                ('objet_id', models.IntegerField(blank=True, null=True)),
                ('details', models.JSONField(default=dict, help_text="Détails de l'action")),
                ('donnees_avant', models.JSONField(blank=True, default=dict, null=True)),
                ('donnees_apres', models.JSONField(blank=True, default=dict, null=True)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('duree_action', models.FloatField(blank=True, help_text='Durée en secondes', null=True)),
                ('conforme_rgpd', models.BooleanField(default=True)),
                ('conforme_hipaa', models.BooleanField(default=True)),
                ('conforme_cdp', models.BooleanField(default=True)),
                ('alerte_generee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.alerteconformite')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit de conformité',
                'verbose_name_plural': 'Audits de conformité',
                'ordering': ['-date_action'],
                'indexes': [models.Index(fields=['utilisateur', 'date_action'], name='api_auditco_utilisa_7a94db_idx'), models.Index(fields=['type_action', 'date_action'], name='api_auditco_type_ac_4317a2_idx'), models.Index(fields=['objet', 'objet_id'], name='api_auditco_objet_d1ec6a_idx')],
            },
        ),
    ]
